/* Automatically generated by wasm2c */
#ifndef BANK_H_GENERATED_
#define BANK_H_GENERATED_

#include <stdint.h>

#include "wasm-rt.h"

/* TODO(binji): only use stdint.h types in header */
#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif


/* import: 'main' 'wasm_abort' */
extern void (*Z_mainZ_wasm_abort)(void);
void Z_bank_init(void);
void Z_bank_free(void);

/* export: 'memory' */
extern wasm_rt_memory_t (*Z_bankZ_memory);
/* export: 'deposit_money' */
extern void (*Z_bankZ_deposit_money)(u64);

  /* export: 'can_buy_candy' */
extern u32 Z_bankZ_can_buy_candy(void);
/* export: 'buy_candy' */
extern void Z_bankZ_buy_candy(void);

/* export: 'candy_pieces' */
extern u64 (*Z_bankZ_candy_pieces)(void);

#ifdef __cplusplus
}
#endif

#endif  /* BANK_H_GENERATED_ */
