/* Automatically generated by wasm2c */
#ifndef MAIN_H_GENERATED_
#define MAIN_H_GENERATED_

#include <stdint.h>

#include "wasm-rt.h"

/* TODO(binji): only use stdint.h types in header */
#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct Z_bank_module_instance_t;
struct Z_env_module_instance_t;

typedef struct Z_main_module_instance_t {
  struct Z_bank_module_instance_t* Z_bank_module_instance;
  struct Z_env_module_instance_t* Z_env_module_instance;
  u32 w2c___stack_pointer;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_table_t w2c_T0;

  /* import: 'bank' 'buy_candy' */
  struct Z_bank_module_instance_t* Z_bank_module_instance_buy_candy;
  void (*Z_bankZ_buy_candy)(struct Z_bank_module_instance_t*);

  /* import: 'bank' 'can_buy_candy' */
  struct Z_bank_module_instance_t* Z_bank_module_instance_can_buy_candy;
  u32 (*Z_bankZ_can_buy_candy)(struct Z_bank_module_instance_t*);
} Z_main_module_instance_t;

void Z_main_init_module(void);
  void Z_main_instantiate(Z_main_module_instance_t*, struct Z_bank_module_instance_t*, struct Z_env_module_instance_t*, void (*bc)(struct Z_bank_module_instance_t*), u32 (*cbc)(struct Z_bank_module_instance_t*));
void Z_main_free(Z_main_module_instance_t*);

/* import: 'bank' 'candy_pieces' */
u64 Z_bankZ_candy_pieces(struct Z_bank_module_instance_t*);
/* import: 'bank' 'deposit_money' */
void Z_bankZ_deposit_money(struct Z_bank_module_instance_t*, u64);
/* import: 'env' 'abort' */
void Z_envZ_abort(struct Z_env_module_instance_t*);
/* import: 'env' 'printf' */
u32 Z_envZ_printf(struct Z_env_module_instance_t*, u32, u32);

/* export: 'memory' */
wasm_rt_memory_t* Z_mainZ_memory(Z_main_module_instance_t* module_instance);
/* export: 'main' */
u32 Z_mainZ_main(Z_main_module_instance_t*);
/* export: 'wasm_abort' */
void Z_mainZ_wasm_abort(Z_main_module_instance_t*);

#ifdef __cplusplus
}
#endif

#endif  /* MAIN_H_GENERATED_ */
